export enum EndPoints {
  list_music = 'ux-mobile/desuka/music',
  detail_music = 'ux-mobile/desuka/music/',
  search_general = 'ux-mobile/desuka/search',
  like_music = 'ux-mobile/desuka/musicLike',
  list_category = 'ux-mobile/desuka/categoryMusic',
  register = 'ux-mobile/desuka/register',
  verify = 'ux-mobile/desuka/verify',
  login = 'ux-mobile/desuka/login',
  logout = 'ux-mobile/desuka/logout',
  sendMessage = 'ux-mobile/desuka/messages',
  createConversation = 'ux-mobile/desuka/conversations',
  getAllConversationChat = 'ux-mobile/desuka/conversations/',
  getAllChatxUser = 'ux-mobile/desuka/messages/',
  profileUser = 'ux-mobile/desuka/profile',
  followUser = 'ux-mobile/desuka/follow',
  unfollowUser = 'ux-mobile/desuka/unfollow',
  getAllFollowers = 'ux-mobile/desuka/followers/',
  getAllFollowing = 'ux-mobile/desuka/following/',
  isFollowUser = 'ux-mobile/desuka/is-following/',
}
